# Generated by Django 3.1.3 on 2020-12-02 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('purchase_code', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase_total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('Em validação', 'Em validação'), ('Aprovado', 'Aprovado')], default='Em validação', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_art', models.DateTimeField(auto_now=True)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
