# Generated by Django 3.1.3 on 2020-11-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('purchase_code', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase_total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_date', models.DateField()),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('status', models.CharField(default='Em validação', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_art', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
