# Generated by Django 3.1.3 on 2020-11-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0002_auto_20201123_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='purchase_total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
