# Generated by Django 3.1.3 on 2020-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0003_auto_20201124_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='cashback_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='cashback_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
