# Generated by Django 3.1.3 on 2020-11-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0004_auto_20201124_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='compras',
            name='cashback_percent',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='cashback_value',
        ),
    ]
