# Generated by Django 3.1.3 on 2020-11-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0005_auto_20201124_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='status',
            field=models.CharField(choices=[('EV', 'Em validação'), ('AP', 'Aprovado')], default='Em validação', max_length=15),
        ),
    ]
