# Generated by Django 3.1.3 on 2020-11-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0006_auto_20201125_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='status',
            field=models.CharField(choices=[('EV', 'Em validação'), ('AP', 'Aprovado')], default='EV', max_length=15),
        ),
    ]
