# Generated by Django 3.1.3 on 2020-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0007_auto_20201125_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='status',
            field=models.CharField(choices=[('Em validação', 'Em validação'), ('Aprovado', 'Aprovado')], default='Em validação', max_length=15),
        ),
    ]
